[package]
name = "pubky-swiss-knife"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
base64 = "0.22"
dioxus = { version = "0.7.0-rc.1", features = ["desktop"] }
dioxus-desktop = "0.7.0-rc.1"
mimalloc = "0.1"
pubky = "0.6.0-rc.6"
url = "2.5"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
qrcode = "0.13"
rfd = "0.14"

[dev-dependencies]
tempfile = "3"
