[package]
name = "portable-homeserver"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
base64 = "0.22"
directories = "6"
dioxus = { version = "0.7.0-rc.1", features = ["desktop"] }
pubky-homeserver = "0.6.0-rc.6"
pubky-testnet = "0.6.0-rc.6"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal", "fs"] }
toml = "0.8"

[patch.crates-io]
pubky-homeserver = { path = "../vendor/pubky-homeserver/pubky-homeserver-0.6.0-rc.6" }

[dev-dependencies]
tempfile = "3"

