[package]
name = "portable-homeserver"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
base64 = "0.22.1"
directories = "6.0.0"
dioxus = { version = "0.7.0-rc.1", features = ["desktop"] }
pubky-homeserver = "0.6.0-rc.6"
pubky-testnet = "0.6.0-rc.6"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread", "signal", "fs", "time"] }
toml = "0.9.8"
tracing = "0.1.41"

[dev-dependencies]
tempfile = "3.23.0"
